frontend/controllers/CabinetController.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/14/2021
 * Time: 8:44 PM
 */

namespace frontend\controllers;

use common\models\Settings;
use common\models\User;
use common\services\MoneyOperationsService;
use frontend\services\OpenBoxService;
use Yii;
use yii\web\Controller;

class CabinetController extends Controller
{
    /**
     * @param $action
     * @return bool|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }
        return parent::beforeAction($action);
    }

    public function actionIndex(){

        if(Yii::$app->session->get('win')){
            Yii::$app->session->setFlash('success', Yii::$app->session->get('win'));
            Yii::$app->session->remove('win');
        }

        return $this->render('index',[
           'user'=>User::find()->with(['moneyPrices','userPresent'])->where(['id'=>Yii::$app->user->id])->one(),
           'course'=>Settings::findOne(2)->value,
            'error'=>$_GET['error']??null
        ]);
    }

    /**
     * @return \yii\web\Response
     * @throws \Exception
     */
    public function actionOpen(){
        $win = OpenBoxService::open();

        Yii::$app->session->set('win',$win);
        return $this->redirect('/cabinet?win='.$win);
    }

    /**
     * @return \yii\web\Response
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionExchange(){

        if(MoneyOperationsService::exchangeMoney()){

            Yii::$app->session->setFlash('success', "Бонусы начислены!");
            return $this->redirect('/cabinet');
        }else{
            return $this->redirect('/cabinet?error='.urlencode('Недостаточно денег на счету'));
        }
    }
}

frontend/views/cabinet/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $user \common\models\User */
/* @var $course float */
/* @var $error string */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Кабинет пользователя';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Откройте подарок!</h1>

        <?=Html::a('Открыть!','/cabinet/open',['class'=>'btn btn-success'])?>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <p><b>Ваши данные: </b></p>
                <p><?=$user->username?></p>
                <p><?=$user->email?></p>
                <p>Выигрышные деньги: </p>
                <?php
                if($user->moneyPrices){
                foreach ($user->moneyPrices as $winningMoney){
                ?>
                    <p>Сумма: <?=$winningMoney->amount?> Переведено на счет: <?=$winningMoney->sent?'да':'нет'?></p>
                    <?php
                }
                }else{
                    echo '<p>Выигранных денег пока нет</p>';
                }?>
            </div>
            <div class="col-lg-4">
                <p><b>Бонусы: <?=$user->bonus_amount?></b></p>
                <p>Вы можете обменять ваши деньги на бонусы: </p>
                <p>Курс: 1 к <?=$course?></p>
                <?php $form = ActiveForm::begin(['method'=>'post','action'=>'/cabinet/exchange']); ?>
                <?=Html::textInput('exchange','',['class'=>'form-control','placeholder'=>'Введите сумму'])?>
                <p style="color:red;display: <?=$error?'block':'none'?>"><b><?=$error?></b></p>
                <?=Html::button('Обменять',['class'=>'btn btn-primary','type'=>'submit'])?>
                <?php ActiveForm::end(); ?>
            </div>
            <div class="col-lg-4">
                <p><b>Ваши подарки: </b></p>
                <?php
                if($user->userPresent){
                    foreach ($user->userPresent as $present){
                        ?>
                <div class="row">
                    <div class="col-sm-6"><?=$present->present->name?></div>
                    <div class="col-sm-4">Количество: <?=$present->count?></div>
                </div>
                <?php
                    }
                }else{
                    echo '<p>Подарков пока нет</p>';
                }?>
            </div>
        </div>

    </div>
</div>